-- Optional hackathon shortcut: create the PostgreSQL schema directly.
-- Preferred path remains: dotnet ef migrations add InitialCreate && dotnet ef database update

CREATE TABLE IF NOT EXISTS "Users" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FullName" text NOT NULL,
  "Email" text NOT NULL,
  "PhoneNumber" text NOT NULL,
  "PasswordHash" text NOT NULL,
  "FaydaFanHash" text,
  "FaydaVerified" boolean NOT NULL DEFAULT false,
  "CreatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_PhoneNumber" ON "Users" ("PhoneNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_FaydaFanHash" ON "Users" ("FaydaFanHash") WHERE "FaydaFanHash" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "Circles" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" text NOT NULL,
  "ContributionAmount" numeric(18,2) NOT NULL,
  "Frequency" integer NOT NULL,
  "MemberLimit" integer NOT NULL,
  "Status" integer NOT NULL,
  "OrganizerId" integer NOT NULL,
  "StartDate" timestamptz,
  "CreatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "FK_Circles_Users_OrganizerId" FOREIGN KEY ("OrganizerId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "CircleMemberships" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CircleId" integer NOT NULL,
  "UserId" integer NOT NULL,
  "RoleInCircle" text NOT NULL,
  "PayoutOrder" integer,
  "JoinedAt" timestamptz NOT NULL DEFAULT now(),
  "MembershipStatus" integer NOT NULL,
  CONSTRAINT "FK_CircleMemberships_Circles_CircleId" FOREIGN KEY ("CircleId") REFERENCES "Circles"("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_CircleMemberships_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CircleMemberships_CircleId_UserId" ON "CircleMemberships" ("CircleId", "UserId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CircleMemberships_CircleId_PayoutOrder" ON "CircleMemberships" ("CircleId", "PayoutOrder") WHERE "PayoutOrder" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "Rounds" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CircleId" integer NOT NULL,
  "RoundNumber" integer NOT NULL,
  "ReceiverMembershipId" integer NOT NULL,
  "Status" integer NOT NULL,
  "OpenedAt" timestamptz NOT NULL DEFAULT now(),
  "PaidOutAt" timestamptz,
  "PayoutAmount" numeric(18,2),
  CONSTRAINT "FK_Rounds_Circles_CircleId" FOREIGN KEY ("CircleId") REFERENCES "Circles"("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_Rounds_CircleMemberships_ReceiverMembershipId" FOREIGN KEY ("ReceiverMembershipId") REFERENCES "CircleMemberships"("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Rounds_CircleId_RoundNumber" ON "Rounds" ("CircleId", "RoundNumber");

CREATE TABLE IF NOT EXISTS "Payments" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoundId" integer NOT NULL,
  "MembershipId" integer NOT NULL,
  "Amount" numeric(18,2) NOT NULL,
  "PaidAt" timestamptz NOT NULL DEFAULT now(),
  "ReferenceNote" text,
  "RecordedByUserId" integer NOT NULL,
  CONSTRAINT "FK_Payments_Rounds_RoundId" FOREIGN KEY ("RoundId") REFERENCES "Rounds"("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_Payments_CircleMemberships_MembershipId" FOREIGN KEY ("MembershipId") REFERENCES "CircleMemberships"("Id") ON DELETE RESTRICT,
  CONSTRAINT "FK_Payments_Users_RecordedByUserId" FOREIGN KEY ("RecordedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Payments_RoundId_MembershipId" ON "Payments" ("RoundId", "MembershipId");

CREATE TABLE IF NOT EXISTS "Payouts" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoundId" integer NOT NULL,
  "ReceiverMembershipId" integer NOT NULL,
  "Amount" numeric(18,2) NOT NULL,
  "PaidAt" timestamptz NOT NULL DEFAULT now(),
  "ConfirmedByUserId" integer NOT NULL,
  "Status" integer NOT NULL,
  CONSTRAINT "FK_Payouts_Rounds_RoundId" FOREIGN KEY ("RoundId") REFERENCES "Rounds"("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_Payouts_CircleMemberships_ReceiverMembershipId" FOREIGN KEY ("ReceiverMembershipId") REFERENCES "CircleMemberships"("Id") ON DELETE RESTRICT,
  CONSTRAINT "FK_Payouts_Users_ConfirmedByUserId" FOREIGN KEY ("ConfirmedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Payouts_RoundId" ON "Payouts" ("RoundId");

CREATE TABLE IF NOT EXISTS "OtpVerifications" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" integer NOT NULL,
  "PhoneNumber" text NOT NULL,
  "OtpHash" text NOT NULL,
  "ExpiresAt" timestamptz NOT NULL,
  "VerifiedAt" timestamptz,
  "Attempts" integer NOT NULL DEFAULT 0,
  CONSTRAINT "FK_OtpVerifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_OtpVerifications_UserId_VerifiedAt" ON "OtpVerifications" ("UserId", "VerifiedAt");
